# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5646320ef34b7887ce4ec195006c64cd3caf13f3cb430f437a1df221e828fa0bda1b5291fb9455310ced10e5e587a6b7bed5dbdac6503682d52c1c2a6451d8f8

test:
  secret_key_base: c726f0dced086511398d0a5f870686f82a2775519c8269e5eea3721d45070727fa1dbe6e54094430c10993754e2bc5b80c467b97699cccf67c3611c39206e24c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
